# Generated by Django 4.2.3 on 2023-07-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customMovies', '0002_movie_synopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='synopsis',
            new_name='overview',
        ),
    ]
