# Generated by Django 4.2.3 on 2023-07-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customMovies', '0004_movie_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created'], 'verbose_name': 'pelicula', 'verbose_name_plural': 'peliculas'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movies', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(null=True, verbose_name='Valoración media'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tittle',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
